### ISSUE TITLE
Use same random ID suffix for injection of one SVG

### ISSUE THREAD

**Issue by iconexperience** [iconfu/svg-inject#1]
Within an SVG the IDs must be unique. ID collision can only happen between two injected SVGs. Therefore, when making IDs unique, it is sufficient to use the same random suffix for each ID withing one injected SVG, which has the following benefits:

- Only one random string has to be created for each injection, instead of creating a random string for each ID (slightly improved performance)
- We can store the random suffix as an attribute in the injected SVG, which can then be accessed through Javascript. After injection the randomized IDs can easily be found by using their original ID and adding the suffix that can be read from the `<svg>` element. This way it is still possible to access the elements through Javascript after injection.

**Comment by dasboe** [comment]
Point 1:
Implemented in 3544702e0f1ad5e123e49de8567e549ce49527b2 

All ids inside an SVG are made unique by appending one unique suffix "--inject-XXXXXXXX" for each injected SVG, where XXXXXXXX is a random alphanumeric string of length 8

Point 2:
Because there is no obvious use case for an attribute containing the inject suffix and because SVGInject should stay as small as possible not planing to implement this by now.
