### ISSUE TITLE
Handle empty and missing `src` attributes gracefully

### ISSUE THREAD

**Issue by waruyama** [iconfu/svg-inject#15]
Currently `img` elements with empty or missing `src` attributes do not work, because the way we convert relative URLs to absolute URLs does not work for empty strings. 

On Chrome and Firefox an `img` with an empty `src` attribute is displayed as a broken image. An `img` without a `src` attribute is displayed as an empty image on Chrome and not displayed at all on Firefox.
Here is a codepen: https://codepen.io/anon/pen/KGNepr

We should probably leave the `src` attribute untouched if it is empty or not provided.

**Comment by dasboe** [comment]
Fixed in 675ed14261cc934494b9cad2425ec19cb5e520cf with different behaviour for empty and not set `src` attribute:

(1) The `src` attribute is empty
There is be no injection and no call to `onFail` options hook. The `src` attribute may be set  dynamically later and trigger the `onload` event and the injection of the dynamically set SVG

(2) The src attribute is empty
Tries to load the empty src and trigger the `onFail` options hook with a status `"SVG_INVALID"`

This will be part of Version 1.1.1
