### ISSUE TITLE
SVG's not always loading in

### ISSUE THREAD

**Issue by bobcat4848** [iconfu/svg-inject#26]
I've been trying to get this to work in my project, but it was been really spotty. I have the script included in my html and the minified js file in my project. I can style it, but sometimes the image doesn't get turned into an SVG. Sometimes it decides to inject and then other times it just doesn't seem to want to. I can simply refresh the page and it seems pretty random that some will load into an svg and others won't. If I can possibly get a solution for this, that'd be awesome! I'm using the latest version and I followed the example snippet on the projects homepage to implement it.

Under scripts:
`<script src="/scripts/svg-inject.min.js"></script>
`

In the body of the html:
`    <a href="#" class="slendr-prev"><img src="images/icons/angle-left.svg" onload="SVGInject(this)"/></a>
    <a href="#" class="slendr-next"><img src="images/icons/angle-right.svg" onload="SVGInject(this)"/></a>`

SVG styling:
`      svg {
        fill: white;
        width: 2rem;
        height: 2rem;
      }`

**Comment by dasboe** [comment]
Is the `svg-inject.min.js` script included before each `<img>` element? If the script is included at a later place it could lead to your described behaviour, because when `onload` is triggered `SVGInject` might not be accessible yet. The recommended place to include the `svg-inject.min.js` script is inside the `<head>` of your document. (https://github.com/iconfu/svg-inject#manually)

If this is not your problem could you please provide a little bit more information:

- Which browser and version do you use?
- Can you see any error messages in console of the browser development tools?
- Is it possible to provide the SVGs you are using?

**Comment by bobcat4848** [comment]
Your description really helped solve our issue. My team and I are using Hugo and it was including the scripts at the bottom of the page, but we were able to move them above into the head and it fixed it. Thank you!
